// <auto-generated />
using System;
using CyprusAgriculture.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyprusAgriculture.API.Migrations
{
    [DbContext(typeof(CyprusAgricultureDbContext))]
    [Migration("20251103210409_FixFarmIdTypeInSampleParticipant")]
    partial class FixFarmIdTypeInSampleParticipant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyprusAgriculture.API.Models.Farm", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<decimal?>("AnnualProductionValue")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_production_value");

                    b.Property<string>("Community")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("community");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EconomicSize")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("economic_size");

                    b.Property<string>("FarmCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("farm_code");

                    b.Property<string>("FarmType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("farm_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("LegalStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("legal_status");

                    b.Property<string>("LivestockTypes")
                        .HasColumnType("text")
                        .HasColumnName("livestock_types");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("MainCrops")
                        .HasColumnType("text")
                        .HasColumnName("main_crops");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("province");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("SizeCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("size_category");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("numeric")
                        .HasColumnName("total_area");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.HasIndex("FarmCode")
                        .IsUnique()
                        .HasDatabaseName("ix_farms_farm_code");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delivery_error");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<string>("LogoAlignment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("logo_alignment");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("participation_status");

                    b.Property<string>("PlainTextContent")
                        .HasColumnType("text")
                        .HasColumnName("plain_text_content");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_id");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<bool>("SendImmediately")
                        .HasColumnType("boolean")
                        .HasColumnName("send_immediately");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StyleSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("style_settings");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invitations_created_by");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_invitations_participant_id");

                    b.HasIndex("QuestionnaireId")
                        .HasDatabaseName("ix_invitations_questionnaire_id");

                    b.HasIndex("SampleId")
                        .HasDatabaseName("ix_invitations_sample_id");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_locations_parent_id");

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-a1b2-c3d4e5f67890"),
                            Code = "01",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(2430),
                            IsActive = true,
                            Latitude = 35.1855659,
                            Longitude = 33.382276400000002,
                            Name = "Λευκωσία",
                            Type = "region"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4890-b2c3-d4e5f6a78901"),
                            Code = "02",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(3550),
                            IsActive = true,
                            Latitude = 34.675306200000001,
                            Longitude = 33.029300499999998,
                            Name = "Λεμεσός",
                            Type = "region"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4901-c3d4-e5f6a7b89012"),
                            Code = "03",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(3560),
                            IsActive = true,
                            Latitude = 34.917597100000002,
                            Longitude = 33.633963399999999,
                            Name = "Λάρνακα",
                            Type = "region"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4012-d4e5-f6a7b8c90123"),
                            Code = "04",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(3560),
                            IsActive = true,
                            Latitude = 34.7766904,
                            Longitude = 32.438426700000001,
                            Name = "Πάφος",
                            Type = "region"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4123-e5f6-a7b8c9d01234"),
                            Code = "05",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(3560),
                            IsActive = true,
                            Latitude = 35.126440700000003,
                            Longitude = 33.946379800000003,
                            Name = "Αμμόχωστος",
                            Type = "region"
                        });
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentResponses")
                        .HasColumnType("integer")
                        .HasColumnName("current_responses");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TargetResponses")
                        .HasColumnType("integer")
                        .HasColumnName("target_responses");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questionnaires");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_questionnaires_created_by");

                    b.HasIndex("ThemeId")
                        .HasDatabaseName("ix_questionnaires_theme_id");

                    b.ToTable("questionnaires", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.QuestionnaireInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declined_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitationToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("invitation_token");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_invitations");

                    b.HasIndex("QuestionnaireId")
                        .HasDatabaseName("ix_questionnaire_invitations_questionnaire_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_questionnaire_invitations_user_id");

                    b.ToTable("questionnaire_invitations", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.QuestionnaireQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_count");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipality");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_quotas");

                    b.HasIndex("QuestionnaireId")
                        .HasDatabaseName("ix_questionnaire_quotas_questionnaire_id");

                    b.ToTable("questionnaire_quotas", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.QuestionnaireResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FarmName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("farm_name");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipality");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("postal_code");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_id");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_data");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_responses");

                    b.HasIndex("QuestionnaireId")
                        .HasDatabaseName("ix_questionnaire_responses_questionnaire_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_questionnaire_responses_user_id");

                    b.ToTable("questionnaire_responses", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentSize")
                        .HasColumnType("integer")
                        .HasColumnName("current_size");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FilterCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_criteria");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TargetSize")
                        .HasColumnType("integer")
                        .HasColumnName("target_size");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_samples");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_samples_created_by");

                    b.HasIndex("QuestionnaireId")
                        .HasDatabaseName("ix_samples_questionnaire_id");

                    b.ToTable("samples", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.SampleParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_data");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farm_id");

                    b.Property<string>("InclusionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("inclusion_reason");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<int>("SelectionPriority")
                        .HasColumnType("integer")
                        .HasColumnName("selection_priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sample_participants");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_sample_participants_farm_id");

                    b.HasIndex("SampleId")
                        .HasDatabaseName("ix_sample_participants_sample_id");

                    b.ToTable("sample_participants", (string)null);
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_themes");

                    b.ToTable("themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4234-f6a7-b8c9d0e12345"),
                            Category = "Crops",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(6860),
                            Description = "Ερωτηματολόγια σχετικά με καλλιέργειες, σπόρους, λιπάσματα",
                            IsActive = true,
                            Name = "Φυτική Παραγωγή"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-4345-a7b8-c9d0e1f23456"),
                            Category = "Livestock",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(7430),
                            Description = "Ερωτηματολόγια για ζωικό κεφάλαιο και ζωική παραγωγή",
                            IsActive = true,
                            Name = "Κτηνοτροφία"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4456-b8c9-d0e1f2a34567"),
                            Category = "Fisheries",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(7430),
                            Description = "Ερωτηματολόγια για αλιευτικές δραστηριότητες",
                            IsActive = true,
                            Name = "Αλιεία"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-4567-c9d0-e1f2a3b45678"),
                            Category = "Irrigation",
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(7430),
                            Description = "Ερωτηματολόγια για αρδευτικά συστήματα",
                            IsActive = true,
                            Name = "Άρδευση"
                        });
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Organization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(8190),
                            Email = "admin@agriculture.gov.cy",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "User",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 11, 3, 21, 4, 8, 882, DateTimeKind.Utc).AddTicks(8980),
                            Email = "user@agriculture.gov.cy",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "User",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Invitation", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_created_by");

                    b.HasOne("CyprusAgriculture.API.Models.SampleParticipant", "Participant")
                        .WithMany("Invitations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invitations_sample_participants_participant_id");

                    b.HasOne("CyprusAgriculture.API.Models.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_questionnaires_questionnaire_id");

                    b.HasOne("CyprusAgriculture.API.Models.Sample", "Sample")
                        .WithMany("Invitations")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_samples_sample_id");

                    b.Navigation("Creator");

                    b.Navigation("Participant");

                    b.Navigation("Questionnaire");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Location", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_locations_locations_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Questionnaire", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.User", "Creator")
                        .WithMany("CreatedQuestionnaires")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaires_users_created_by");

                    b.HasOne("CyprusAgriculture.API.Models.Theme", "Theme")
                        .WithMany("Questionnaires")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_questionnaires_themes_theme_id");

                    b.Navigation("Creator");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.QuestionnaireInvitation", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.Questionnaire", "Questionnaire")
                        .WithMany("Invitations")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_invitations_questionnaires_questionnaire_id");

                    b.HasOne("CyprusAgriculture.API.Models.User", "User")
                        .WithMany("Invitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_invitations_users_user_id");

                    b.Navigation("Questionnaire");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.QuestionnaireQuota", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.Questionnaire", "Questionnaire")
                        .WithMany("Quotas")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_quotas_questionnaires_questionnaire_id");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.QuestionnaireResponse", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.Questionnaire", "Questionnaire")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_responses_questionnaires_questionnaire_id");

                    b.HasOne("CyprusAgriculture.API.Models.User", "User")
                        .WithMany("Responses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_responses_users_user_id");

                    b.Navigation("Questionnaire");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Sample", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_samples_users_created_by");

                    b.HasOne("CyprusAgriculture.API.Models.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_samples_questionnaires_questionnaire_id");

                    b.Navigation("Creator");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.SampleParticipant", b =>
                {
                    b.HasOne("CyprusAgriculture.API.Models.Farm", "Farm")
                        .WithMany("SampleParticipants")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sample_participants_farms_farm_id");

                    b.HasOne("CyprusAgriculture.API.Models.Sample", "Sample")
                        .WithMany("Participants")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sample_participants_samples_sample_id");

                    b.Navigation("Farm");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Farm", b =>
                {
                    b.Navigation("SampleParticipants");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Questionnaire", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Quotas");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Sample", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.SampleParticipant", b =>
                {
                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.Theme", b =>
                {
                    b.Navigation("Questionnaires");
                });

            modelBuilder.Entity("CyprusAgriculture.API.Models.User", b =>
                {
                    b.Navigation("CreatedQuestionnaires");

                    b.Navigation("Invitations");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
